# Generated by Django 5.2 on 2025-04-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=128)),
                ('contenu', models.CharField(max_length=255)),
                ('publicationDate', models.DateField()),
                ('auteur', models.CharField(max_length=64)),
            ],
        ),
    ]
