# Generated by Django 5.2 on 2025-04-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=32)),
                ('createDate', models.PositiveSmallIntegerField()),
                ('couleur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='monApp3.couleur')),
            ],
        ),
    ]
