# Generated by Django 5.2 on 2025-04-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_pays_president'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='president',
            name='country',
        ),
        migrations.DeleteModel(
            name='Pays',
        ),
        migrations.DeleteModel(
            name='President',
        ),
    ]
